# Generated by Django 4.0.4 on 2023-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_remove_trainee_address_remove_trainee_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('long_text', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
